export const menuArray = [
  {
    name: "Classic Cheeseburger",
    ingredients: [
      "Beef patty",
      "cheddar cheese",
      "lettuce",
      "tomato",
      "house sauce",
    ],
    category: "burgers",
    id: 0,
    price: 12,
    image: "Images/Classic-hamburger.png",
  },
  {
    name: "Double Smash",
    ingredients: [
      "Two beef patties",
      "American cheese",
      "pickles",
      "grilled onions",
    ],
    category: "burgers",
    price: 15,
    image: "Images/Double-smash.png",
    id: 1,
  },
  {
    name: "Jimmy's Original",
    ingredients: [
      "Beef patty",
      "cheddar",
      "bacon",
      "caramelized onions",
      "BBQ sauce",
    ],
    category: "burgers",
    price: 14,
    image: "Images/Jimmys-original.png",
    id: 2,
  },
  {
    name: "Fries",
    ingredients: ["Crispy fries", "sea salt"],
    category: "sides",
    price: 5,
    image: "Images/Fries.png",
    id: 3,
  },
  {
    name: "Onion Rings",
    ingredients: ["Beer-battered onion rings"],
    category: "sides",
    price: 5,
    image: "Images/Onion-rings.png",
    id: 4,
  },
  {
    name: "Chicken Bites",
    ingredients: ["Breaded chicken", "classic seasoning"],
    category: "sides",
    price: 5,
    image: "Images/Chicken-bites.png",
    id: 5,
  },
  {
    name: "Vanilla Milkshake",
    ingredients: ["Vanilla ice cream", "milk"],
    category: "desserts",
    price: 8,
    image: "Images/Vanilla-milkshake.png",
    id: 6,
  },
  {
    name: "Chocolate Milkshake",
    ingredients: ["Chocolate ice cream", "milk"],
    category: "desserts",
    price: 8,
    image: "Images/Chocolate-milkshake.png",
    id: 7,
  },
];
